# Generated by Django 3.2 on 2021-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='active',
            field=models.BooleanField(choices=[(True, True), (False, False)], default=1),
        ),
    ]
